# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Wänglöf's blog
email: jwanglof@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Johan Wänglöf's blog about a bunch of technical stuff that he's learning, or just wants to share
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jwanglof.github.io" # the base hostname & protocol for your site
twitter_username: jwanglof
github_username:  jwanglof

# Build settings
markdown: kramdown
